# Settings b5: locator source + exact b4 carry — PREPARED / NOT_RUN

Implementation `270cfdfa2bcbd04ef62a6ad3ecbc22358db32d67`, actual clean metadata HEAD `20957ebb0df3bbeb907aa3c654eeaa55f71f573d` in `codex/web-message-settings`. Root scoped locator approval is `/tmp/root-message-settings-270c-locator-source-review.json` (SHA a96a893b8ef870da4bcb5d3e12eb4156b4829e2e3f8c3f2f80f5e25f74826abe). Full feature remains UNKNOWN. The only project source delta from the actual b4 run is the named fieldset locator with count/visibility checks; five other sources are unchanged. No project file is changed by this preparation.

This NEW owned candidate is `/private/tmp/msgset-b5`; original executed b4 files/gate/raw remain byte-identical. Worker, aliases, runtime config and the actual carried budget are copied byte-for-byte. Parent has one narrow executable change: its previous-result cleanup equality now requires EXACTLY the actual b4 five fields: errors=[], groupAbsent=true, workerGroupAbsent=true, chromeGroupAbsent=true, scratchAbsent=true. The old three-field equality would reject b4's two extra ownership facts. It is not weakened to subset checks and does not rewrite b4 evidence. Manager explicitly accepted this source-only correction for independent review; `supervisor.py.diff` contains the complete executable delta.

Carry: 20,609ms used of 60,000; 39,391ms remaining = 24,391ms work +15,000ms cleanup. The byte-identical browser-budget.json is the actual completed b4 result and still references b4. Previous retained evidence is 741,839B from its parent result SHA `f0a78f25bf3acb5a0b4c55639a1252b75943473fcdb6d841af2d74da8ef7d02c`, including old attempts; new candidate/raw are additionally counted. Temporary/profile cap remains 64MiB and retained evidence cap remains 8MiB, start free 1GiB+128MiB / stop 1GiB+64MiB. Polling is observational, not a hard disk quota or an exclusive attribution of free-space changes.

Authority and ownership are unchanged: native Chrome sibling keeps Chrome's own sandbox and its owned short profile/cache/MAC_CHROMIUM_TMPDIR/BREAKPAD_DUMP_LOCATION, but is outside the custom outer OS write/egress restriction. Node remains under the custom sandbox. The parent owns two separate process groups, records actual exits/log EOF, checks resources after reap/before deletion and after result/budget writes, and only removes owned scratch after both groups are absent. No guarantee under SIGKILL is claimed. No personal profile or library access is added by the candidate, but the absence of the outer Chrome restriction is a real difference and must remain explicitly accepted.

New parent bytes mean the old b4 exact boundary acceptance is NOT reused. Binding state=PREPARED, nativeChromeBoundaryApproval=null, no gate, no result or scratch; executable worker hash is unchanged. Root must review the delta and pin the new exact runner/worker boundary under existing GO authorization, and manager must supply fresh source/claim/dependency/resource/shared-window admission before any execution. Prepared state already fails closed before reading a gate.

Validation here is text/byte/hash comparison and manual clean-code review only. No candidate execution, syntax/import parser, Node, types/direct, HTTP, Chrome, PG, free-space sampling, install or dependency write. All actual browser scenarios remain unrerun. This preparation is not a retry or a runtime approval.
