import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const projectRoot = fileURLToPath(new URL('../../../', import.meta.url));
const roots = '/Users/citrine/Projects/AgentHarness/Flow-worktrees';
const assignments = [
  ['GDEP01', '目标依赖材料批量读取', '工作线', 'goal-dependency-batch', 'gdep01-dependency-batch'],
  ['WPF-DASHBOARD-TIMING02', '任务时间与事项阅读', '工程协作', 'dashboard-task-timing-readability', 'wpf-dashboard-timing-readability'],
  ['WPF-WORKSPACEARC01', '可组合的会话工作区', '工作线', 'web-workspace-composition', 'wpf-workspace-arc'],
  ['X01-VERIFIER-ADMISSION-RESULT01', '插件验证受理与结果归属', '工作线', 'plugin-verifier-admission-result', 'x01-verifier-admission-result'],
  ['S01Q01', '暂停会话扫描过滤', '工作线', 'queue-paused-scan', 's01q01-paused-queue'],
  ['X01-REMOVAL-REFERENCES-CLIENT', '插件引用的客户端读取', '工作线', 'plugin-removal-references-client', 'x01-removal-references-client'],
  ['X01-ARTIFACT-VERIFIER01', '安装式产物验证接口', '工作线', 'plugin-artifact-verifier', 'x01-artifact-verifier'],
  ['X01-TRUSTED-PROCESS-HOST01', '受信插件独立进程执行', '工作线', 'plugin-trusted-process-host', 'x01-trusted-process-host'],
  ['SVC06B', '恢复网页配套的固定后台', '工作线', 'backend-browser-recovery', 'svc06-browser-recovery'],
  ['SVC09A', '旧聊天与消息设置并行运行', '工作线', 'personal-message-settings', 'svc09-message-settings-activation'],
  ['WPF-MESSAGESETTINGS03', '聊天消息设置实际接入', '工作线', 'web-message-settings-app', 'wpf-message-settings-app'],
  ['X01-VERSION-LIFECYCLE01', '插件版本升级回滚验收', '工作线', 'plugin-version-lifecycle', 'x01-version-lifecycle'],
  ['X01-REMOVAL-REFERENCES01', '插件材料保留与移除依据', '工作线', 'plugin-removal-references', 'x01-removal-references'],
  ['X01-UPSTREAM-UPGRADE01', '插件上游版本升级', '工作线', 'plugin-upstream-upgrade', 'x01-upstream-upgrade'],
  ['X01-PLUGIN-COMMAND-ACK01', '插件命令回执校验', '工作线', 'plugin-command-acks', 'x01-plugin-command-acks'],
  ['X01-HOST-CANDIDATES-CLIENT01', '插件宿主目录与终端入口', '工作线', 'plugin-host-candidates', 'x01-host-candidates-client'],
  ['WPF-PLUGIN-RUNTIME01', '插件启停与运行状态', '工作线', 'web-plugin-runtime-management', 'wpf-plugin-runtime-management'],
  ['X01-CLI-COMMANDS01', '插件管理终端命令', '工作线', 'plugin-cli-commands', 'x01-cli-commands'],
  ['MATURE06-READBOUND01', '客户端响应读取上限', '工作线', 'client-read-bounds', 'mature06-client-read-bounds'],
  ['OPS-METER01', '有界资源计量与验证复用', '工程协作', 'owned-resource-measurement', 'ops-meter01-resource-measurement'],
  ['MATURE06-LAZY01', '推理正文按需读取', '工作线', 'lazy-reasoning-reads', 'mature06-lazy-reasoning'],
  ['SVC09', '保留旧页面的新版本发布', '工作线', 'personal-release-policy', 'svc09-personal-release-policy'],
  ['WPF-DASHBOARD-TIMING01', '任务开始完成与等待时间', '工程协作', 'dashboard-task-timing', 'wpf-dashboard-task-timing'],
  ['SVC08', '个人网页连接释放与持续可用', '工作线', 'personal-web-connection-lifecycle', 'svc08-web-connection-lifecycle'],
  ['WPF-DASHBOARD-ACCESS01', '本机产品入口与连接资料', '工程协作', 'dashboard-local-access', 'wpf-dashboard-local-access'],
  ['OPS-CI01', '远程最小合同验证准备', '工程协作', 'ops-remote-validation', 'ops-ci01-remote-validation'],
  ['CHAT05P01', '工具完整原文保存与读取', '工作线', 'native-activity-body', 'chat05p01-native-activity-body'],
  ['CHAT05P02', '工具全文公开读取与运行时接入', '工作线', 'native-activity-body-wiring', 'chat05p02-native-activity-body-wiring'],
  ['S01P08', '原生流式授权检查收敛', '工作线', 'native-stream-ownership', 's01p08-native-stream-ownership'],
  ['WPF-MESSAGESETTINGS02', '聊天快速设置控件', '工作线', 'web-message-settings-quick-controls', 'wpf-message-settings-quick-controls'],
  ['OPS14', '有界进程监督与可靠收尾', '工程协作', 'owned-process-supervision', 'ops14-owned-process-supervision'],
  ['MATURE02C02', 'Codex会话连续性', '工作线', 'codex-conversation-continuity', 'wpf-mature-02-codex-continuity'],
  ['REQ15', '会话页面批量读取', '工作线', 'conversation-turn-page-batch', 'req15-conversation-turn-page-batch'],
  ['S01P07', '领取回执与崩溃恢复', '工作线', 'runner-claim-recovery', 's01p07-runner-claim-recovery'],
  ['SVC07', '事务连接失效与安全释放', '工作线', 'server-transaction-disconnect', 'svc07-transaction-recovery'],
  ['WPF-DPERF05', '看板更新时间兼容', '工程协作', 'dashboard-status-timestamps', 'wpf-dperf05-status-timestamps'],
  ['SVC05R01', '保留网页与新后台兼容', '技术验证', 'personal-retained-web-compatibility', 'svc05-retained-web-compatibility'],
  ['O16', '连续目标的原生验收', '技术验证', 'continuous-native-goal-acceptance', 'o16-continuous-goal-acceptance'],
  ['WPF-MESSAGESETTINGS01', '每条消息的执行设置', '工作线', 'web-message-settings', 'wpf-message-settings'],
  ['WPF-PROFILEC02', '聊天配置只读兼容', '工作线', 'web-profile-readonly-compatibility', 'wpf-profile-readonly-compatibility'],
  ['CHAT06P03', '减少流式正文重复哈希', '工作线', 'assistant-stream-runner-hash', 'chat06-runner-prefix-hash'],
  ['MATURE02C01', '逐消息设置共享接口与命令行', '工作线', 'claude-message-settings-client', 'mature02c01-claude-message-settings-client'],
  ['WPF-DPERF04', '看板首页摘要与按需详情', '工程协作', 'dashboard-summary-detail', 'wpf-dperf04-summary-detail'],
  ['TUI01G', '终端逐消息执行设置', '工作线', 'tui-message-settings', 'tui01g-message-settings'],
  ['TUI01F', '终端显式取消与双端接续', '工作线', 'tui-task-cancel', 'tui01f-task-cancel'],
  ['WPF-MATURE-02-CORE', 'Claude逐消息设置契约', '工作线', 'claude-settings-claim-eligibility', 'wpf-mature-02-message-settings-core'],
  ['SVC05H01', '现用后台的附件历史兼容', '工作线', 'personal-history-compatibility', 'svc05-history-compatibility'],
  ['O15', '确认完整输入后推进目标', '工作线', 'goal-input-confirmation', 'o15-goal-input-confirmation'],
  ['WPF-RECOVERY01', '刷新后恢复聊天与草稿', '工作线', 'web-conversation-recovery', 'wpf-conversation-recovery'],
  ['WPF-RELEASE03', '新版网页与现有后台兼容', '技术验证', 'web-current-preview-compatibility', 'wpf-release03-current-preview'],
  ['O14', '授权后持续推进依赖任务', '工作线', 'goal-persistent-progression', 'o14-goal-progression'],
  ['COST01A', '有来源的执行用量说明', '工作线', 'cost-usage-readout', 'cost01a-usage-readout'],
  ['S01P06', '执行等待与资源释放', '工作线', 'runner-wait-bounds', 's01p06-runner-wait'],
  ['O13', '从目标到计划与文本交付', '工作线', 'continuous-goal-journey', 'o13-continuous-goal-journey'],
  ['TUI01E', '终端队列控制与断线续接', '工作线', 'tui-queue-controls', 'tui01e-queue-controls'],
  ['WPF-CONNECTION01', '刷新后恢复中心连接', '工作线', 'browser-connection-session', 'wpf-connection-session'],
  ['S01P05', '执行事件状态写入优化', '工作线', 'event-state-persistence', 's01p05-event-state'],
  ['ENG01J', '真实受限工程写入宿主', '工作线', 'engineering-native-authority', 'eng01j-native-write-authority'],
  ['ENG01K', '受信单文件工具写入', '工作线', 'engineering-trusted-tool-writer', 'eng01k-trusted-tool-writer'],
  ['ENG01L', '只读原生与受信写入组合', '工作线', 'engineering-readonly-tool-host', 'eng01l-readonly-tool-host'],
  ['ENG01I', '受信原生工程宿主编排', '工作线', 'engineering-native-host', 'eng01i-native-engineering-host'],
  ['SVC06', '后台固定版本与依赖发布', '工作线', 'backend-release', 'svc06-backend-release'],
  ['ENG01H', '原生工程用途与检查收据', '工作线', 'engineering-native-contract', 'eng01h-native-engineering-contract'],
  ['TUI01D', '终端目标与控制旅程', '工作线', 'tui-goal-session', 'tui01d-goal-session'],
  ['WPF-DPERF03', '看板读取并发与快照复用', '工程协作', 'dashboard-git-snapshot', 'wpf-dperf03'],
  ['WPF-ATTACHI02', '附件随聊天可靠发送', '工作线', 'web-attachment-production', 'wpf-attach-i02-production-binding'],
  ['SVC05', '新版个人预览兼容准备', '工作线', 'personal-current-release', 'svc05-current-release'],
  ['ENG01G', '原生工程写入组合', '工作线', 'engineering-native-writer', 'eng01g-native-writer'],
  ['O12', '持续目标会话与解释历史', '工作线', 'goal-session-controller', 'o12-goal-session'],
  ['ENG01F', '工程快照与可信检查收据', '工作线', 'engineering-calculator-receipt', 'eng01f-calculator-receipt'],
  ['WPF-DASHSUM01', '看板目标摘要与详情', '工程协作', 'dashboard-human-summary', 'wpf-dashboard-summary'],
  ['WPF-WORKSPACECACHE01', '聊天页面回收与恢复', '工作线', 'web-workspace-cache', 'wpf-workspace-cache'],
  ['ENG01E', '工程源码与检查报告边界', '工作线', 'engineering-native-checker', 'eng01e-trusted-calculator-checker'],
  ['O11', '目标计划与交付统一读取', '工作线', 'goal-delivery-read-model', 'o11-goal-delivery-read-model'],
  ['ENG01D', '原生工程身份与执行接缝', '工作线', 'engineering-native-seams', 'eng01d-native-writer-seams'],
  ['ENG01C', '工程写入停止与检查边界', '工作线', 'engineering-writer-settlement', 'eng01c-writer-settlement'],
  ['S01P04', '执行器读取与领取隔离', '工作线', 'runner-read-fence', 's01p04-runner-read-fence'],
  ['WPF-ATTACHI01', '附件选择与上传恢复', '工作线', 'web-attachment-input-preview', 'wpf-attach-i01-input-preview'],
  ['WPF-RELEASE02', '网页发布检查类型修正', '工作线', 'web-release-type-fix', 'wpf-release02-tuple-types'],
  ['WPF-WORKSPACEPERF01', '双面板打开与切换测量', '技术验证', 'web-workspace-lifecycle-baseline', 'wpf-workspace-lifecycle-baseline'],
  ['WPF-ACK01', '网页共用发送确认', '工作线', 'web-shared-ack-consumer', 'wpf-ack01-shared-consumer'],
  ['ENG01B', '工程执行配置与恢复', '工作线', 'engineering-execution-profile', 'eng01b-engineering-profile'],
  ['TUI01C', '终端逐段正文与工具详情', '工作线', 'tui-stream-activity', 'tui01c-stream-activity'],
  ['WPF-RELEASE01', '真实网页发布兼容验证', '技术验证', 'web-release-recovery', 'wpf-release01-product-compatibility'],
  ['WPF-DPERF02', '看板固定源码核验复用', '工作线', 'dashboard-proof-batching', 'wpf-dashboard-proof-batching'],
  ['S01P03', '执行器停止与领取排空', '工作线', 'runner-graceful-stop', 's01-graceful-stop'],
  ['TUI01B', '终端与网页共用发送确认', '工作线', 'shared-conversation-ack', 'tui01b-shared-ack'],
  ['ENG01A', '受管工作区与工程检查', '工作线', 'engineering-workspace-pipeline', 'eng01a-workspace-pipeline'],
  ['WPF-ATTACH01', '文本附件资源与引用', '工作线', 'attachment-resources', 'wpf-attach01-resources'],
  ['R05D', 'Codex可信启动配置', '工作线', 'codex-native-launch', 'r05d-codex-launch'],
  ['S01P02', '执行器并发配置入口', '工作线', 'runner-concurrency-entry', 's01-concurrency-entry'],
  ['D08', '两层任务关系展示', '工程协作', 'dashboard-task-links', 'd08-task-links'],
  ['WPF-ACTIVITYREAD01', '工具活动阅读简化', '工作线', 'web-activity-readability', 'wpf-activity-readability'],
  ['WPF-STEIRI01', '运行中补充指令接入', '工作线', 'web-steering-integration', 'wpf-steer-i01-integration'],
  ['SVC04', '网页独立发布与回退', '工作线', 'web-artifact-release', 'svc04-web-release'],
  ['ENG-001', '真实工程任务交付', '总体计划', 'engineering-delivery', 'eng01-engineering-delivery'],
  ['R05C', 'Codex普通执行与未知状态', '工作线', 'codex-native-adapter', 'r05c-codex-native-adapter'],
  ['TUI01A', '终端会话与可靠发送', '工作线', 'tui-conversations', 'tui01a-conversations'],
  ['TUI-001', '可日用终端客户端', '总体计划', 'tui-client', 'tui01-terminal-client'],
  ['COST-001', '执行成本与预算解释', '总体计划', 'execution-cost', 'cost01-execution-cost'],
  ['R05B', 'Codex中心身份与来源校验', '工作线', 'native-center-policy', 'r05b-native-center-policy'],
  ['WPF-MATURE-01', '成熟双主题视觉', '总体计划', 'web-platform-management', 'wpf-mature-01-visual'],
  ['WPF-MATURE-02', 'Claude与Codex执行选项', '总体计划', 'claude-codex-capabilities', 'wpf-mature-02-harness-capabilities'],
  ['WPF-MATURE-03', '附件与文件输入', '总体计划', 'web-platform-management', 'wpf-mature-03-attachments'],
  ['WPF-MATURE-04', '上下文用量与压缩透明', '总体计划', 'context-transparency', 'wpf-mature-04-context-transparency'],
  ['WPF-MATURE-05', '单标签双面板工作区', '总体计划', 'web-platform-management', 'wpf-mature-05-workspace'],
  ['WPF-MATURE-06', '完整聊天可靠性', '总体计划', 'web-platform-management', 'wpf-mature-06-chat'],
  ['R06', 'Codex本机通信与退出', '工作线', 'codex-native-transport', 'r06-codex-native-transport'],
  ['WPF-CONTEXTI01', '知识引用接入聊天', '工作线', 'web-context-integration', 'wpf-context-i01-integration'],
  ['WPF-STEER01', '运行中补充指令控件', '工作线', 'web-steering-control', 'wpf-steering-control'],
  ['WPF-VISUAL01', '圆角与双主题界面', '工作线', 'web-shared-overlays', 'wpf-visual01-shell'],
  ['R05', '可替换的原生执行工具接口', '工作线', 'native-harness-host', 'r05-native-harness-host'],
  ['CHATUI01', '真实逐段正文界面验收', '技术验证', 'stream-ui-acceptance', 'chatui01-stream-acceptance'],
  ['D05FIT01', '架构图首次打开适配', '工作线', 'dashboard-architecture-first-fit', 'd05-first-fit'],
  ['SVC03', '固定版本的真实网页预览', '工作线', 'static-preview', 'svc03-static-preview'],
  ['WPF-CHATREAD01', '聊天正文阅读空间', '工作线', 'web-conversation-readability', 'wpf-chat-readability'],
  ['CHAT10', '补充指令受理状态', '工作线', 'steering-admission-readiness', 'chat10-steering-readiness'],
  ['WPF-CONTEXT02', '知识引用随消息可靠发送', '工作线', 'web-context-receipts', 'wpf-context-receipts'],
  ['O10', '原生文本子任务验收准备', '技术验证', 'native-child-acceptance', 'o10-native-child-acceptance'],
  ['S01P01', '同一执行器并发任务', '工作线', 'runner-attempt-pool', 's01-attempt-pool'],
  ['CHAT09', '补充指令执行配置核验', '工作线', 'steering-profile-admission', 'chat09-steering-admission'],
  ['CHAT06P02', '正文存储传输优化', '工作线', 'assistant-stream-prefix-hash', 'chat06-prefix-hash'],
  ['O09', '原生执行单个目标节点', '工作线', 'native-goal-node-execution', 'o09-native-node-execution'],
  ['WPF-CHAT06I01', '聊天逐段正文接入', '工作线', 'web-conversation-stream-integration', 'wpf-chat06-stream-integration'],
  ['WPF-CONTEXT01', '聊天知识引用选择', '工作线', 'web-knowledge-selection', 'wpf-context01-knowledge-selection'],
  ['WPF-PERF03', '聊天消息复用', '工作线', 'web-message-reuse', 'wpf-perf03-message-reuse'],
  ['CHAT08', '原生对话中的补充指令', '工作线', 'native-active-steering', 'chat08-native-active-steering'],
  ['CHAT06P01', '流式正文存储成本测量', '技术验证', 'assistant-stream-cost-probe', 'chat06-stream-cost'],
  ['WPF-CHAT06S01', '聊天逐段正文读取', '工作线', 'web-conversation-stream', 'wpf-chat06-stream'],
  ['WPF-ACTIVITYC01', '活动列表分页兼容', '工作线', 'web-activity-cursor-compatibility', 'wpf-activity-cursor-compatibility'],
  ['CHAT07', '执行中的修订指令', '工作线', 'active-steering', 'chat07-active-steering'],
  ['WPF-ACTIVITYI01', '聊天工具活动接入', '工作线', 'web-conversation-activity-integration', 'wpf-activity-i01-integration'],
  ['O08', '原生目标规划验收', '技术验证', 'native-graph-acceptance', 'o08-native-graph-acceptance'],
  ['CHAT06C02', '流式正文与旧页面兼容', '工作线', 'assistant-stream-compatibility', 'chat06c02-stream-compatibility'],
  ['WPF-CHAT06C01', '聊天流式能力兼容', '工作线', 'web-stream-compatibility', 'wpf-chat06-compatibility'],
  ['S01', '实际执行容量验证', '技术验证', 'runner-capacity-probe', 's01-runner-capacity'],
  ['WPF-RENDERERI01', '聊天可插拔详情接入', '工作线', 'web-data-renderer-integration', 'wpf-renderer-i01-integration'],
  ['CHAT06', '助手正文逐步显示', '工作线', 'native-assistant-stream', 'chat06-assistant-stream'],
  ['X05', '可恢复的包下载', '工作线', 'plugin-package-fetches', 'x05-package-fetch-operations'],
  ['WPF-QUEUE01', '聊天待发送消息', '工作线', 'web-conversation-queue', 'wpf-queue01-ui'],
  ['K01', '项目知识原文与检索', '工作线', 'knowledge-source-store', 'k01-knowledge-sources'],
  ['WPF-PROFILEUX01', '聊天配置摘要优化', '工作线', 'web-execution-profile-summary', 'wpf-profileux-execution-summary'],
  ['SVC02', '真实预览安全更新', '工作线', 'preview-refresh', 'svc02-preview-refresh'],
  ['FLOW-001', '产品与技术架构', '总体计划', 'plan-status-review', 'flow-001-architecture'],
  ['FLOW-002', 'Provider 与 Harness', '技术验证', 'plan-status-review', 'flow-002-provider-harness'],
  ['FLOW-003', 'M1 执行与验收', '里程碑', 'plan-status-review', 'flow-003-m1-execution'],
  ['OPS-001', '计划状态与审查规范', '工程协作', 'plan-status-review', 'ops-001-status-review'],
  ['C01', '控制中心', '工作线', 'm1-control-plane', 'c01-control-plane', 'server'],
  ['R01', '执行 Runner', '工作线', 'm1-runner', 'r01-runner', 'runner'],
  ['R02', '原生 Harness', '工作线', 'm1-native-harness', 'r02-native-harness'],
  ['L01', '命令行', '工作线', 'm1-cli', 'l01-cli', 'cli'],
  ['W01', '产品 Web', '工作线', 'm1-web', 'w01-web', 'web'],
  ['D01', '工程进度', '工作线', 'execution-dashboard', 'd01-execution-dashboard', 'execution-dashboard'],
  ['I02', 'M2 恢复与跨任务集成', '集成验证', 'm2-integration', 'i02-integration'],
  ['I01', 'M1 集成验收', '工作线', 'm1-integration', 'i01-integration'],
  ['LAB01', '性能样例', '技术验证', 'performance-probes', 'lab01-performance'],
  ['LAB02', '多观察端样例', '技术验证', 'observer-probes', 'lab02-observer-probes'],
  ['D02', '进度来源同步', '工作线', 'dashboard-progress-sync', 'd02-progress-sync'],
  ['C02', '异常核对与恢复', '工作线', 'm2-reconciliation', 'c02-reconciliation'],
  ['P01', '协议互操作', '工作线', 'protocol-adapters', 'p01-protocols'],
  ['D03', '进度的人类视图', '工作线', 'dashboard-human-view', 'd03-dashboard-human'],
  ['WPF-001', 'Web 平台持续执行', '工程协作', 'web-platform-management', 'web-platform'],
  ['WPF-M02', 'Web统一工作入口', '工作线', 'web-unified-workspace', 'wpf-m02-web-workspace'],
  ['WPF-P01', 'Web插件宿主', '工作线', 'web-plugin-host', 'wpf-p01-plugin-host'],
  ['O01', '目标与版本化执行', '工作线', 'goal-orchestration', 'o01-goal-orchestration'],
  ['WPF-PERF01', 'Web性能基线测量', '技术验证', 'web-performance', 'wpf-perf01-web-performance'],
  ['E01', 'Harness 零模型验证', '技术验证', 'harness-auth-probes', 'e01-harness-probes'],
  ['WPF-I01', 'Web 插件集成', '工作线', 'web-plugin-runtime-app', 'wpf-i01-plugin-integration'],
  ['X01', '插件管理计划', '工作线', 'plugin-enable-binding', 'x01-plugin-management'],
  ['R03', '远端Runner租约可靠性', '工作线', 'runner-reliability', 'r03-runner-reliability'],
  ['B01', '分层读取性能与界限', '技术验证', 'task-read-projections', 'b01-bounded-reads'],
  ['X02', '插件中心登记与命令', '工作线', 'plugin-registry', 'x02-plugin-registry'],
  ['WPF-PERF02', '活动窗口与阅读稳定', '工作线', 'web-activity-window', 'wpf-perf02-activity-window'],
  ['CHAT02', '真实助手正文事件', '工作线', 'conversation-native-events', 'chat02-native-messages'],
  ['WPF-CHAT01', '产品持续对话', '工作线', 'web-conversations', 'wpf-chat01-conversations'],
  ['CHAT01', '持久对话与回复', '工作线', 'conversation-center', 'chat01-conversations'],
  ['CHAT03', '执行选项与能力', '工作线', 'execution-profiles', 'chat03-execution-profiles'],
  ['R04', '中心有界停机', '工作线', 'center-shutdown', 'r04-center-shutdown'],
  ['P03', '外部协议传输优化', '工作线', 'protocol-payload', 'p03-protocol-payload'],
  ['X03', '插件管理视图', '工作线', 'plugin-management', 'x03-plugin-management-view'],
  ['SVC01', '个人真实聊天预览', '工作线', 'personal-preview', 'svc01-personal-preview'],
  ['CTX01', '上下文内核合成验证', '技术验证', 'context-kernel-probe', 'ctx01-context-kernel'],
  ['WPF-PROFILE01', '对话执行选项', '工作线', 'web-execution-profiles', 'wpf-profile01-execution-profiles'],
  ['O02', '原生目标工具桥接', '工作线', 'native-goal-tools', 'o02-native-goal-tools'],
  ['D06', '架构固定快照更新', '工程协作', 'dashboard-architecture-runtime', 'd06-architecture-refresh'],
  ['CHAT04', '持久消息队列', '工作线', 'conversation-queue', 'chat04-conversation-queue'],
  ['WPF-QUEUE00', '旧新队列能力兼容', '工作线', 'web-queue-compatibility', 'wpf-queue00-compatibility'],
  ['O03', '目标工具执行授权', '工作线', 'goal-tool-authorization', 'o03-goal-tool-authorization'],
  ['WPF-RENDERER01', '对话详情展示', '工作线', 'web-data-renderers', 'wpf-renderer01-data-renderers'],
  ['CHAT05', '原生工具活动', '工作线', 'native-activity', 'chat05-native-activity'],
  ['X04', '固定版本包产物', '工作线', 'package-artifacts', 'x04-package-artifacts'],
  ['K03', '目标节点知识引用', '工作线', 'goal-knowledge-context', 'k03-goal-knowledge-context'],
  ['WPF-ACTIVITY01', '聊天工具活动展示', '工作线', 'web-conversation-activity', 'wpf-activity01'],
  ['WPF-K02C01', '聊天上下文兼容', '工作线', 'web-context-compatibility', 'wpf-k02-compatibility'],
  ['K02', '聊天知识上下文', '工作线', 'conversation-context', 'k02-conversation-context'],
  ['O07', '原生目标拆分工具', '工作线', 'native-graph-tools', 'o07-native-graph-tools'],
  ['O06', '目标拆分受限授权', '工作线', 'goal-graph-runs', 'o06-goal-graph-runs'],
  ['O05', '目标拆分提案与应用', '工作线', 'goal-graph-proposals', 'o05-goal-graph-proposals'],
  ['O04', '原生目标工具运行', '工作线', 'native-goal-execution', 'o04-native-goal-bridge'],
  ['B02', '对话读取成本测量', '技术验证', 'conversation-read-cost', 'b02-conversation-read-cost'],
  ['B03', '长对话预览读取优化', '工作线', 'bounded-conversation-preview', 'b03-bounded-preview'],
  ['D07', '下一交付与完成片段', '工程协作', 'dashboard-delivery-stage', 'd07-delivery-stage'],
  ['WPF-PROFILEI01', '聊天执行选项接入', '工作线', 'web-profile-integration', 'wpf-profile-integration'],
  ['WPF-DPERF01', '看板刷新重复核验优化', '工作线', 'dashboard-proof-performance', 'wpf-dashboard-proof-performance'],
  ['CTX02', '原生上下文插件兼容', '技术验证', 'context-pi-hook-probe', 'ctx02-pi-hook'],
  ['WPF-X03I01', '插件管理产品接线', '工作线', 'web-plugin-management-integration', 'wpf-x03-plugin-integration'],
  ['D05', '代码架构视图', '工程协作', 'dashboard-architecture', 'd05-architecture-view'],
  ['D04', '多 Lead 领取协调', '工程协作', 'dashboard-coordination', 'd04-coordination'],
  ['F01', '共享领域接口', '工作线', 'm2-shared-foundation', 'f01-shared-domains'],
  ['G01', '版本化项目计划', '工作线', 'project-graph', 'g01-project-graph'],
  ['P02', '持久外部调度', '工作线', 'protocol-dispatch', 'p02-durable-protocol'],
  ['M02', '统一工作入口', '工作线', 'm2-workspace', 'm02-unified-workspace'],
];

export function defaultRegistry() {
  return {
    mainWorktree: '/Users/citrine/Projects/AgentHarness/Flow',
    fallbackWorktree: projectRoot,
    frozenCommit: 'eacee76fa7f1b6cc46b06b57ae68458637be4a26',
    staleAfterHours: 24,
    phaseSourceId: 'FLOW-001',
    tasks: assignments.map(([id, title, role, directory, plan, app]) => ({
      id, title, role, worktree: path.join(roots, directory),
      branch: `codex/${directory}`, planDir: `plans/${plan}`,
      evidenceDir: `docs/evidence/${({ 'GDEP01': 'gdep01-dependency-batch', 'WPF-DASHBOARD-TIMING02': 'wpf-dashboard-timing-readability', 'WPF-WORKSPACEARC01': 'wpf-workspace-arc', 'X01-VERIFIER-ADMISSION-RESULT01': 'x01-verifier-admission-result', 'S01Q01': 's01q01-paused-queue', 'WPF-I01': 'wpf-i01', 'X01-REMOVAL-REFERENCES-CLIENT': 'x01-removal-references-client', 'X01-ARTIFACT-VERIFIER01': 'x01-artifact-verifier', 'X01-TRUSTED-PROCESS-HOST01': 'x01-trusted-process-host', 'SVC06B': 'svc06', 'SVC09A': 'svc09', 'WPF-MESSAGESETTINGS03': 'wpf-message-settings-app', 'X01-VERSION-LIFECYCLE01': 'x01-version-lifecycle', 'X01-REMOVAL-REFERENCES01': 'x01-removal-references', 'X01-UPSTREAM-UPGRADE01': 'x01-upstream-upgrade', 'X01-PLUGIN-COMMAND-ACK01': 'x01-plugin-command-acks', 'X01-HOST-CANDIDATES-CLIENT01': 'x01-host-candidates-client', 'WPF-PLUGIN-RUNTIME01': 'wpf-plugin-runtime-management', 'X01-CLI-COMMANDS01': 'x01-cli-commands', 'OPS-METER01': 'ops-meter01', 'MATURE06-LAZY01': 'mature06-lazy-reasoning', 'WPF-DASHBOARD-TIMING01': 'wpf-dashboard-task-timing', 'WPF-DASHBOARD-ACCESS01': 'wpf-dashboard-local-access', 'WPF-MESSAGESETTINGS02': 'wpf-message-settings-quick-controls', 'REQ15': 'req15-turn-page-batch', 'WPF-DPERF05': 'wpf-dperf05', 'SVC05R01': 'svc05-retained-web-compatibility', 'WPF-MESSAGESETTINGS01': 'wpf-message-settings', 'WPF-PROFILEC02': 'wpf-profile-readonly-compatibility', 'WPF-DPERF04': 'wpf-dperf04', 'TUI01F': 'tui01f', 'WPF-MATURE-02-CORE': 'wpf-mature-02-message-settings-core', 'SVC05H01': 'svc05-history-compatibility', 'WPF-RECOVERY01': 'wpf-conversation-recovery', 'WPF-RELEASE03': 'wpf-release03', 'WPF-CONNECTION01': 'wpf-connection-session', 'WPF-ATTACHI02': 'wpf-attach-i02', 'WPF-DASHSUM01': 'wpf-dashboard-summary', 'WPF-WORKSPACECACHE01': 'wpf-workspace-cache', 'WPF-ATTACHI01': 'wpf-attach-i01', 'WPF-RELEASE02': 'wpf-release02', 'WPF-WORKSPACEPERF01': 'wpf-workspace-lifecycle-baseline', 'WPF-ACK01': 'wpf-ack01', 'WPF-DPERF02': 'wpf-dashboard-proof-batching', 'WPF-ACTIVITYREAD01': 'wpf-activity-readability', 'WPF-STEIRI01': 'wpf-steer-i01', 'ENG-001': 'eng01', 'TUI-001': 'tui01', 'COST-001': 'cost01', 'WPF-MATURE-01': 'web-platform', 'WPF-MATURE-02': 'wpf-mature-02', 'WPF-MATURE-03': 'web-platform', 'WPF-MATURE-04': 'wpf-mature-04', 'WPF-MATURE-05': 'web-platform', 'WPF-MATURE-06': 'web-platform', 'WPF-CONTEXTI01': 'wpf-context-i01', 'WPF-STEER01': 'wpf-steering-control', 'WPF-VISUAL01': 'wpf-visual01', 'D05FIT01': 'd05fit01', 'WPF-001': 'web-platform', 'WPF-X03I01': 'wpf-x03', 'WPF-PROFILEI01': 'wpf-profile-integration', 'WPF-PROFILEUX01': 'wpf-profileux', 'WPF-K02C01': 'wpf-k02-compatibility', 'WPF-RENDERERI01': 'wpf-renderer-i01', 'WPF-CHAT06C01': 'wpf-chat06-compatibility', 'WPF-ACTIVITYI01': 'wpf-activity-i01', 'WPF-ACTIVITYC01': 'wpf-activity-cursor-compatibility', 'WPF-CHAT06S01': 'wpf-chat06-stream', 'WPF-CHAT06I01': 'wpf-chat06-stream-integration', 'WPF-PERF03': 'wpf-perf03', 'WPF-CONTEXT02': 'wpf-context-receipts', 'WPF-CHATREAD01': 'wpf-chat-readability' })[id] ?? id.toLowerCase()}`,
      ...(app ? { appEvidence: `apps/${app}/EVIDENCE.md` } : {}),
    })),
  };
}

export function validateRegistry(registry) {
  if (!Array.isArray(registry.tasks) || registry.tasks.length === 0) throw new Error('登记必须包含 tasks');
  if (!path.isAbsolute(registry.mainWorktree) || !path.isAbsolute(registry.fallbackWorktree)) throw new Error('登记根路径必须为绝对路径');
  if (!/^[a-f0-9]{40}$/.test(registry.frozenCommit)) throw new Error('frozenCommit 必须为完整 SHA');
  if (!Number.isFinite(registry.staleAfterHours) || registry.staleAfterHours <= 0) throw new Error('staleAfterHours 必须大于零');
  const ids = new Set();
  for (const task of registry.tasks) {
    if (!/^[A-Z0-9]+(?:-[A-Z0-9]+)*$/.test(task.id) || ids.has(task.id)) throw new Error('任务 ID 必须合法且唯一');
    ids.add(task.id);
    if (!path.isAbsolute(task.worktree) || !task.branch || typeof task.title !== 'string') throw new Error(`任务 ${task.id} 登记不完整`);
    if (!/^plans\/[a-z0-9-]+$/.test(task.planDir)) throw new Error(`任务 ${task.id} planDir 超出范围`);
    if (!/^docs\/evidence\/[a-z0-9-]+$/.test(task.evidenceDir)) throw new Error(`任务 ${task.id} evidenceDir 超出范围`);
    if (task.appEvidence && !/^apps\/[a-z0-9-]+\/EVIDENCE\.md$/.test(task.appEvidence)) throw new Error('appEvidence 超出范围');
  }
  if (registry.phaseSourceId && !ids.has(registry.phaseSourceId)) throw new Error('phaseSourceId 必须指向已登记任务');
  return registry;
}

export async function loadRegistry(filename) {
  return validateRegistry(filename ? JSON.parse(await readFile(filename, 'utf8')) : defaultRegistry());
}
