import { beforeEach, afterEach, expect, it } from 'vitest';
import { randomUUID } from 'node:crypto';
import { startGoalContextFixture } from './fixture.js';
import { transaction } from '../database.js';
import { goalExecutionInputForTask } from './store.js';
let f: Awaited<ReturnType<typeof startGoalContextFixture>>; let ordinal = 0;
beforeEach(async () => { f = await startGoalContextFixture((process.env.FLOW_K03_RUN_LABEL ?? 'recovery') + '-recovery-' + String.fromCharCode(97 + ordinal++), 800); });
afterEach(async () => { await f?.close(); });
it.each(['revised-work', 'no-side-effects'] as const)('preserves frozen knowledge through explicit %s recovery without restoring goal delivery', async strategy => {
  const projectId = await f.project(); const project = (await f.http(`/api/projects/${projectId}`)).body;
  const nodeId = (await f.http(`/api/projects/${projectId}/commands`, { expectedRevision: project.project.revision, reason: 'Recovery node', change: { kind: 'add-node', title: 'Original execution' } })).body.changedNodeId;
  const goalId = (await f.http('/api/goals', { projectId, originalGoal: 'Safe recovery', constraints: 'No external model', acceptance: 'Verified exact output' })).body.goal.id;
  const text = 'word '.repeat(819);
  const source = (await f.http(`/api/projects/${projectId}/knowledge/sources`, { expectedVersion: 0, title: 'Recovery source', text })).body;
  const ref = { projectId, sourceId: source.source.id, version: 1, contentDigest: source.version.contentDigest, locator: { kind: 'utf8-bytes', start: 0, end: Buffer.byteLength(text) } };
  expect((await f.http(`/api/goals/${goalId}/commands`, { kind: 'define-input', nodeId, expectedInputVersion: 0, input: { goal: 'Do initial work', constraints: 'Keep receipts', acceptance: 'Verified', verification: { kind: 'nonempty' }, knowledge: [ref] }, reason: 'Freeze original' })).status).toBe(200);
  const accepted = await f.http(`/api/goals/${goalId}/commands`, { kind: 'execute', nodeId, expectedInputVersion: 1, previousExecutionId: null, dependencies: [], reason: 'Start initial work', fixture: { scenario: 'success', delayMs: 0 } }); expect(accepted.status).toBe(200);
  const taskId = accepted.body.task.id; const original = (await f.http(`/api/tasks/${taskId}`)).body;
  const frozen = await transaction(f.pool, client => goalExecutionInputForTask(client, taskId, original.prompt));
  const runner = (await f.http('/api/runners', { name: 'Recovery fixture', harnesses: ['fixture'], capacity: 1 })).body;
  let assignment: any;
  await expect.poll(async () => { assignment = (await f.http('/api/runner/claim', {}, { token: runner.token })).body.assignment; return assignment; }, { timeout: 3000, interval: 20 }).not.toBeNull();
  expect(assignment.task.id).toBe(taskId); const ownership = { attemptId: assignment.attempt.id, ownerVersion: assignment.attempt.ownerVersion };
  await expect.poll(async () => (await f.http(`/api/tasks/${taskId}`)).body.status, { timeout: 4000, interval: 25 }).toBe('uncertain');
  const resolve = { ...ownership, stoppedConfirmed: true, stopEvidence: { explanation: 'Own fixture process is stopped.', references: [] }, sideEffects: strategy === 'no-side-effects' ? 'none-confirmed' : 'reviewed', effectsEvidence: { explanation: 'Own controlled fixture effects checked.', references: [] }, outcome: 'cancelled' };
  expect((await f.http(`/api/tasks/${taskId}/reconciliation/resolve`, { ...resolve, stoppedConfirmed: false })).status).toBe(400);
  const resolved = await f.http(`/api/tasks/${taskId}/reconciliation/resolve`, resolve); expect(resolved.status).toBe(200);
  const fence = { ...ownership, resolutionId: resolved.body.audit.id };
  const beforeCounts = (await f.pool.query('SELECT (SELECT count(*) FROM flow.tasks) AS tasks,(SELECT count(*) FROM flow.goal_execution_inputs) AS inputs')).rows[0];
  const oversized = await f.http(`/api/tasks/${taskId}/reconciliation/retry`, { ...fence, safety: { strategy: 'revised-work', prompt: 'x'.repeat(12000), evidence: { explanation: 'Reject the total private budget.' } } });
  expect(oversized.status).toBe(409); expect(oversized.body.error.code).toBe('goal_context_budget');
  expect((await f.pool.query('SELECT (SELECT count(*) FROM flow.tasks) AS tasks,(SELECT count(*) FROM flow.goal_execution_inputs) AS inputs')).rows[0]).toEqual(beforeCounts);
  expect((await f.http(`/api/tasks/${taskId}/reconciliation`)).body.audit).toHaveLength(1);
  const safety = strategy === 'revised-work' ? { strategy, prompt: 'Only verify retained output; do not repeat effects.', evidence: { explanation: 'Revised work is a safe owner assertion.', references: [] } } : { strategy, evidence: { explanation: 'No effects were observed in the controlled fixture.', references: [] } };
  const retryBody = { ...fence, safety }; const key = randomUUID(); const path = `/api/tasks/${taskId}/reconciliation/retry`;
  expect(await f.discardReply(path, retryBody, key)).toBe(200); await f.restart();
  const retry = await f.http(path, retryBody, { key }); expect(retry.status).toBe(200); expect(retry.body.replayed).toBe(true);
  expect((await f.http(path, retryBody)).status).toBe(409);
  const recovered = (await f.http(`/api/tasks/${retry.body.task.id}`)).body;
  const input = await transaction(f.pool, client => goalExecutionInputForTask(client, recovered.id, recovered.prompt));
  expect(input!.context.contextDigest).toBe(frozen!.context.contextDigest); expect(input!.context.executionInputDigest).not.toBe(frozen!.context.executionInputDigest);
  expect(input!.prompt).toContain(text); expect(input!.prompt).toContain(resolved.body.audit.id); expect(input!.prompt).toContain(strategy);
  expect(recovered.prompt).not.toContain(text); expect((await f.pool.query('SELECT submission FROM flow.tasks WHERE id=$1', [recovered.id])).rows[0].submission).not.toHaveProperty('resumeSessionId');
  expect((await f.pool.query('SELECT count(*) FROM flow.goal_executions WHERE goal_id=$1', [goalId])).rows[0].count).toBe('1');
  const view = (await f.http(`/api/goals/${goalId}`)).body.nodes[0]; expect(view.execution.task.id).toBe(taskId); expect(view.deliveryCurrent).toBe(false); expect(view.accepted).toBeNull();
});
