import { describe, expect, it, vi } from "vitest";
import { FlowApiError } from "@flow/client";
import { createHash } from "node:crypto";
import type { SteeringAdmission, SteeringCommandInput, SteeringCommandReference, SteeringCommandResult, SteeringState } from "@flow/contracts";
import { createSteeringControl, STEERING_LIMITS, type SteeringPort } from "../src/conversation-steering/control";

const at = "2026-10-06T08:00:00Z", identity = { connectionScope: "connection-A", taskId: "task" };
const ready = (revision = 0, attemptId = "attempt"): SteeringAdmission => ({ taskId: "task", attemptId, ownerVersion: 1, revision, state: "ready", reason: "ready" });
const command = (input: SteeringCommandInput, status: SteeringCommandReference["status"] = "accepted"): SteeringCommandReference => ({ id: `command-${input.attemptId}-${input.expectedRevision+1}`, taskId: "task", attemptId: input.attemptId, ownerVersion: input.ownerVersion, nativeSessionId: "session", revision: input.expectedRevision+1, userMessageUuid: "00000000-0000-4000-8000-000000000001", status, receiptRevision: status === "accepted" ? 0 : 2, input: { bytes: Buffer.byteLength(input.text), digest: createHash("sha256").update(input.text).digest("hex") }, createdAt: at, updatedAt: at });
const input = (revision = 0): SteeringCommandInput => ({ attemptId: "attempt", ownerVersion: 1, expectedRevision: revision, text: `text-${revision}` });
function deferred<T>() { let resolve!: (value: T) => void, reject!: (error: unknown) => void; const promise = new Promise<T>((a,b) => {resolve=a;reject=b;});return {promise,resolve,reject}; }
function setup() {
  let available = ready(), rows: SteeringCommandReference[] = [];
  const port: SteeringPort = {
    admission: vi.fn(async () => available),
    state: vi.fn(async ({ attemptId, after, limit }) => { const selected=rows.filter(r=>r.attemptId===attemptId&&r.revision>after);return {taskId:"task",attemptId,revision:rows.filter(r=>r.attemptId===attemptId).at(-1)?.revision??0,sealed:false,attemptAvailable:true,commands:selected.slice(0,limit),nextCursor:selected.length>limit?selected[limit-1]!.revision:null};}),
    accept: vi.fn(async body => {const row=command(body);rows.push(row);available=ready(row.revision);return {command:row,replayed:false};})
  };
  const control=createSteeringControl(identity,port);
  const open=async()=>{control.updateGate({visible:true,online:true,authorized:true});await control.refresh();};
  return {port,control,open,admission:(r:SteeringAdmission)=>{available=r;},rows:(r:SteeringCommandReference[])=>{rows=r;}};
}
async function settled(s: ReturnType<typeof setup>) { await vi.waitFor(()=>expect(s.control.getSnapshot().receipts.every(r=>r.phase!=="sending")).toBe(true)); await vi.waitFor(()=>expect(s.control.getSnapshot().loading).toBe(false)); }

describe("bound steering control",()=>{
  it("does no reads until explicitly visible, authorized and refreshed; old center remains unavailable",async()=>{const s=setup();await s.control.refresh();expect(s.port.admission).not.toHaveBeenCalled();s.admission({...ready(),state:"unavailable",reason:"disabled"});await s.open();expect(s.port.state).not.toHaveBeenCalled();expect(await s.control.submit("hi")).toBe(false);expect(s.port.accept).not.toHaveBeenCalled();});
  it.each(["", " ", "nul\0", "\ud800", "你".repeat(5462)])("rejects invalid UTF8 before allocating receipt/HTTP: %j",async text=>{const s=setup();await s.open();expect(await s.control.submit(text)).toBe(false);expect(s.control.getSnapshot().receipts).toHaveLength(0);expect(s.port.accept).not.toHaveBeenCalled();});
  it("freezes validated payload and preserves digest/UTF8 identity",async()=>{const s=setup();await s.open();expect(await s.control.submit("你好🙂")).toBe(true);await settled(s);const r=s.control.getSnapshot().receipts[0]!;expect(Object.isFrozen(r.input)).toBe(true);expect(r.bytes).toBe(10);expect(r.phase).toBe("accepted");expect(r.command?.input.digest).toBe(r.digest);});
  it("guards concurrent submit during digest and handles digest rejection",async()=>{const s=setup();await s.open();const d=deferred<ArrayBuffer>();const spy=vi.spyOn(crypto.subtle,"digest").mockReturnValueOnce(d.promise);const first=s.control.submit("one");expect(await s.control.submit("two")).toBe(false);d.reject(Error("digest failed"));expect(await first).toBe(false);expect(s.control.getSnapshot().preparing).toBe(false);expect(s.port.accept).not.toHaveBeenCalled();spy.mockRestore();});
  it("revocation during digest performs zero handoff",async()=>{const s=setup();await s.open();const d=deferred<ArrayBuffer>();const spy=vi.spyOn(crypto.subtle,"digest").mockReturnValueOnce(d.promise);const first=s.control.submit("one");s.control.updateGate({visible:true,online:true,authorized:false});d.resolve(new ArrayBuffer(32));expect(await first).toBe(false);expect(s.port.accept).not.toHaveBeenCalled();spy.mockRestore();});
  it("unknown retries exact key/body despite new admission unavailable and subsequent4xx never erases uncertainty",async()=>{const s=setup();await s.open();vi.mocked(s.port.accept).mockRejectedValueOnce(Error("lost ACK")).mockRejectedValueOnce(new FlowApiError(409,"steering_unavailable","Attempt ended"));await s.control.submit("frozen");await settled(s);const r=s.control.getSnapshot().receipts[0]!;s.admission({...ready(),state:"unavailable",reason:"not-running"});await s.control.refresh();expect(s.control.retry(r.key)).toBe(true);await settled(s);expect(s.control.getSnapshot().receipts[0]?.phase).toBe("unknown");const calls=vi.mocked(s.port.accept).mock.calls;expect(calls[0]![0]).toBe(calls[1]![0]);expect(calls[0]![1]).toBe(calls[1]![1]);s.control.updateGate({visible:true,online:true,authorized:false});expect(s.control.retry(r.key)).toBe(false);});
  it("initial definite CAS rejection refreshes admission without automatic resubmit",async()=>{const s=setup();await s.open();vi.mocked(s.port.accept).mockRejectedValueOnce(new FlowApiError(409,"steering_revision","Refresh revision"));await s.control.submit("stale");await settled(s);expect(s.port.accept).toHaveBeenCalledTimes(1);expect(s.control.getSnapshot().receipts[0]?.phase).toBe("rejected");expect(s.port.admission).toHaveBeenCalledTimes(2);});
  it.each(["task", "attempt", "owner", "revision", "bytes", "digest", "uuid", "session"])("bad ACK %s remains unknown",async field=>{const s=setup();await s.open();vi.mocked(s.port.accept).mockImplementationOnce(async body=>{const r=command(body);if(field==="task")r.taskId="other";if(field==="attempt")r.attemptId="other";if(field==="owner")r.ownerVersion++;if(field==="revision")r.revision++;if(field==="bytes")r.input.bytes++;if(field==="digest")r.input.digest="a".repeat(64);if(field==="uuid")r.userMessageUuid="bad";if(field==="session")r.nativeSessionId="";return{command:r,replayed:false};});await s.control.submit("hi");await settled(s);expect(s.control.getSnapshot().receipts[0]?.phase).toBe("unknown");});
  it("saved accepted replay cannot replace newer observed-consumed metadata",async()=>{const s=setup();await s.open();vi.mocked(s.port.accept).mockRejectedValueOnce(Error("lost"));await s.control.submit("hi");await settled(s);const r=s.control.getSnapshot().receipts[0]!, newer=command(r.input,"observed-consumed");s.rows([newer]);await s.control.refresh();vi.mocked(s.port.accept).mockResolvedValueOnce({command:command(r.input),replayed:true});s.control.retry(r.key);await settled(s);expect(s.control.getSnapshot().receipts[0]?.command?.status).toBe("observed-consumed");});
  it("refreshes every loaded page at same revision to see receipt updates",async()=>{const s=setup(), rows=Array.from({length:25},(_,i)=>command(input(i)));s.rows(rows);await s.open();await s.control.loadMore();expect(s.control.getSnapshot().commands).toHaveLength(25);s.rows(rows.map((r,i)=>i===0?{...r,status:"received",receiptRevision:1}:r));vi.mocked(s.port.state).mockClear();await s.control.refresh();expect(vi.mocked(s.port.state).mock.calls.map(c=>c[0].after)).toEqual([0,20]);expect(s.control.getSnapshot().commands[0]?.status).toBe("received");});
  it("hidden abort preserves unknown original receipt and ignores late result; reconnect can retry",async()=>{const s=setup();await s.open();const d=deferred<SteeringCommandResult>();vi.mocked(s.port.accept).mockReturnValueOnce(d.promise);await s.control.submit("late");const r=s.control.getSnapshot().receipts[0]!;s.control.updateGate({visible:false,online:true,authorized:true});d.resolve({command:command(r.input),replayed:false});await Promise.resolve();expect(s.control.getSnapshot().receipts[0]?.phase).toBe("unknown");expect(s.control.retry(r.key)).toBe(false);await s.open();expect(s.control.retry(r.key)).toBe(true);await settled(s);expect(s.control.getSnapshot().receipts[0]?.phase).toBe("accepted");});
  it("dispose isolates a new center with identical IDs and consumes late rejection",async()=>{const s=setup();const d=deferred<SteeringAdmission>();vi.mocked(s.port.admission).mockReturnValueOnce(d.promise);const open=s.open();await Promise.resolve();expect(s.port.admission).toHaveBeenCalledTimes(1);s.control.dispose();d.reject(Error("late"));await open;const next=setup();await next.open();expect(next.control.getSnapshot().commands).toHaveLength(0);expect(s.control.getSnapshot().commands).toHaveLength(0);});
  it("metadata batches fail atomically on malformed identity and page bounds",async()=>{const s=setup();s.rows([command(input())]);await s.open();const old=s.control.getSnapshot().commands;vi.mocked(s.port.state).mockResolvedValueOnce({taskId:"other",attemptId:"attempt",revision:1,sealed:false,attemptAvailable:true,commands:[],nextCursor:null});await s.control.refresh();expect(s.control.getSnapshot().commands).toEqual(old);expect(s.control.getSnapshot().stale).toBe(true);});
  it("request timeout exposes an error and releases read gate even if port ignores abort",async()=>{vi.useFakeTimers();const timeout=vi.spyOn(AbortSignal,"timeout").mockImplementation(ms=>{const c=new AbortController();setTimeout(()=>c.abort(new DOMException("Timed out","TimeoutError")),ms);return c.signal;});try{const s=setup();vi.mocked(s.port.admission).mockReturnValueOnce(new Promise(()=>{}));const read=s.open();await vi.advanceTimersByTimeAsync(STEERING_LIMITS.timeoutMs+1);await read;expect(s.control.getSnapshot().error).toBeTruthy();expect(s.control.getSnapshot().loading).toBe(false);}finally{timeout.mockRestore();vi.useRealTimers();}});
  it("bounded local receipt capacity rejects new handoff until resolved entries explicitly cleared",async()=>{const s=setup();await s.open();for(let i=0;i<STEERING_LIMITS.receipts;i++){expect(await s.control.submit(`message-${i}`)).toBe(true);await settled(s);}expect(await s.control.submit("keep draft")).toBe(false);expect(s.control.getSnapshot().receipts).toHaveLength(STEERING_LIMITS.receipts);s.control.clearResolved();expect(s.control.getSnapshot().receipts).toHaveLength(STEERING_LIMITS.receipts);s.rows(s.control.getSnapshot().commands.map(r=>({...r,status:"observed-consumed",receiptRevision:2})));await s.control.refresh();s.control.clearResolved();expect(s.control.getSnapshot().receipts).toHaveLength(0);});
  it("unknown receipt cannot be cleared for capacity",async()=>{const s=setup();await s.open();vi.mocked(s.port.accept).mockRejectedValueOnce(Error("lost"));await s.control.submit("unknown");await settled(s);s.control.clearResolved();expect(s.control.getSnapshot().receipts[0]?.phase).toBe("unknown");});
  it("attempt history has a hard bound without dropping uncertain receipts",async()=>{const s=setup();s.admission(ready(0,"attempt-0"));await s.open();vi.mocked(s.port.accept).mockRejectedValue(Error("unknown"));for(let i=0;i<STEERING_LIMITS.attempts;i++){s.admission(ready(0,`attempt-${i}`));await s.control.refresh();expect(await s.control.submit(`message-${i}`)).toBe(true);await settled(s);}s.admission(ready(0,"one-too-many"));await s.control.refresh();expect(s.control.getSnapshot().error).toContain("history is full");expect(await s.control.submit("keep draft")).toBe(false);expect(s.control.getSnapshot().receipts).toHaveLength(STEERING_LIMITS.attempts);s.control.clearResolved();expect(s.control.getSnapshot().receipts).toHaveLength(STEERING_LIMITS.attempts);});
  it("conflicting same receipt revision and changed native identity fail closed without partial publish",async()=>{const s=setup();const initial=command(input());s.rows([initial]);await s.open();s.rows([{...initial,status:"received"}]);await s.control.refresh();expect(s.control.getSnapshot().error).toContain("invalid");expect(s.control.getSnapshot().commands[0]?.status).toBe("accepted");s.rows([{...initial,nativeSessionId:"other"}]);await s.control.refresh();expect(s.control.getSnapshot().commands[0]?.nativeSessionId).toBe("session");});
  it("wrong admission identity never grants sending",async()=>{const s=setup();s.admission({...ready(),taskId:"other"});await s.open();expect(s.control.getSnapshot().admission).toBeUndefined();expect(await s.control.submit("not authorized by this snapshot")).toBe(false);expect(s.port.accept).not.toHaveBeenCalled();});

  it("loading another metadata page cannot make a failed admission refresh fresh",async()=>{const s=setup();s.rows(Array.from({length:25},(_,i)=>command(input(i))));await s.open();vi.mocked(s.port.admission).mockRejectedValueOnce(Error("read failed"));await s.control.refresh();expect(s.control.getSnapshot().stale).toBe(true);await s.control.loadMore();expect(s.control.getSnapshot().commands).toHaveLength(25);expect(s.control.getSnapshot().stale).toBe(true);expect(await s.control.submit("not fresh")).toBe(false);});

  it("a metadata read begun during POST cannot erase the accepted receipt that resolves first",async()=>{
    const s=setup();await s.open();const ack=deferred<SteeringCommandResult>(),page=deferred<SteeringState>();
    vi.mocked(s.port.accept).mockReturnValueOnce(ack.promise);await s.control.submit("interleaved");
    const receipt=s.control.getSnapshot().receipts[0]!;vi.mocked(s.port.state).mockReturnValueOnce(page.promise);
    const reading=s.control.refresh();await vi.waitFor(()=>expect(s.port.state).toHaveBeenCalledTimes(2));
    ack.resolve({command:command(receipt.input),replayed:false});await vi.waitFor(()=>expect(s.control.getSnapshot().receipts[0]?.phase).toBe("accepted"));
    page.resolve({taskId:"task",attemptId:"attempt",revision:0,sealed:false,attemptAvailable:true,commands:[],nextCursor:null});await reading;
    expect(s.control.getSnapshot().commands).toHaveLength(1);expect(s.control.getSnapshot().commands[0]?.id).toBe(s.control.getSnapshot().receipts[0]?.command?.id);
  });
  it("ACK cannot introduce a different native session into the already observed attempt",async()=>{
    const s=setup();s.rows([command(input())]);s.admission(ready(1));await s.open();
    vi.mocked(s.port.accept).mockImplementationOnce(async body=>({command:{...command(body),nativeSessionId:"other-session"},replayed:false}));
    await s.control.submit("next");await settled(s);expect(s.control.getSnapshot().receipts[0]?.phase).toBe("unknown");expect(s.control.getSnapshot().commands).toHaveLength(1);
  });

});
