import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { chromium, expect } from "@playwright/test";
import { startSteeringIntegration } from "./conversation-steering-integration.fixture";
const root=fileURLToPath(new URL("../../../",import.meta.url)),out=root+"docs/evidence/wpf-steer-i01/";
const production=process.argv.includes("--production"),label=production?"production":"development";
const preview=await startSteeringIntegration(production),browser=await chromium.launch({channel:"chrome",headless:true});
const context=await browser.newContext({viewport:{width:1280,height:800},reducedMotion:"reduce"}),page=await context.newPage();page.setDefaultTimeout(10_000);
const checks:string[]=[],errors:string[]=[];let failure:string|null=null;page.on("pageerror",error=>errors.push(error.message));
const surface=()=>page.getByRole("region",{name:"Running task steering",exact:true}).filter({visible:true});
const instruction=()=>surface().getByLabel("Additional instruction",{exact:true});
const pane=(id="chat-2")=>page.locator(`[id="panel-conversation:${id}"]`);
const composer=(id="chat-2")=>pane(id).getByRole("textbox",{name:"Message input",exact:true});
const open=async(id="chat-2")=>{await pane(id).getByRole("button",{name:"Guide running task",exact:true}).click();await expect(instruction()).toBeVisible();await expect(surface().getByRole("button",{name:"Refresh steering",exact:true})).toBeEnabled();};
const hide=async()=>{await surface().getByRole("button",{name:"Hide steering",exact:true}).click();await expect(surface()).toHaveCount(0);};
const select=async(n:number)=>{const nav=page.getByRole("navigation",{name:"Conversations",exact:true});if(!await nav.isVisible())await page.getByRole("button",{name:"Chats",exact:true}).click();await nav.getByRole("button",{name:`Conversation ${n}`,exact:true}).click();await expect(composer(`chat-${n}`)).toBeVisible();};
const posts=()=>preview.calls.filter(call=>call.method==="POST");
const refresh=async()=>{await surface().getByRole("button",{name:"Refresh steering",exact:true}).click();await expect(surface().getByRole("button",{name:"Refresh steering",exact:true})).toBeEnabled();};
const check=async(name:string,run:()=>Promise<void>)=>{await run();checks.push(name);console.log("PASS",name);};
try{
 await page.goto(preview.url);await page.getByLabel("Owner token",{exact:true}).or(page.getByRole("navigation",{name:"Conversations",exact:true})).first().waitFor();if(await page.getByLabel("Owner token",{exact:true}).isVisible()){await page.getByLabel("Owner token",{exact:true}).fill("flow-fixture-only");await page.getByRole("button",{name:"Connect workspace",exact:true}).click();}await select(2);
 await check("real P01 entry is explicit and current-task bound; registration reads zero",async()=>{
  await expect(pane().getByRole("button",{name:"Guide running task",exact:true})).toBeVisible();expect(preview.calls).toHaveLength(0);await composer().fill("Normal composer draft");await composer().press("ControlOrMeta+Shift+Enter");await expect(composer()).toHaveValue("Normal composer draft");expect(posts()).toHaveLength(0);await open();await expect(surface()).toContainText("Task chat-2-task-1");await expect(surface().getByRole("heading",{name:"Running task instruction",exact:true})).toBeFocused();expect(preview.calls.filter(c=>c.path.endsWith("admission"))).toHaveLength(1);await instruction().fill("Independent steering draft");
 });
 await check("same mounted draft survives Hide, native hidden, split/merge and independent B task",async()=>{
  await hide();await expect(pane().getByRole("button",{name:"Guide running task",exact:true})).toBeFocused();await open();await expect(instruction()).toHaveValue("Independent steering draft");await select(3);await expect(surface()).toHaveCount(0);const before=preview.calls.length;await page.waitForTimeout(150);expect(preview.calls).toHaveLength(before);
  await page.getByRole("button",{name:"Split chat",exact:true}).click();await expect(pane()).toBeVisible();await expect(pane("chat-3")).toBeVisible();await open("chat-3");await instruction().fill("B draft");await hide();await open();await expect(instruction()).toHaveValue("Independent steering draft");await expect(composer()).toHaveValue("Normal composer draft");await hide();await page.getByRole("button",{name:"Merge tabs",exact:true}).click();await select(2);await open();await expect(instruction()).toHaveValue("Independent steering draft");
 });
 await check("Enter sends a separate original-key command; unknown retry and late new draft remain independent",async()=>{
  preview.loseNext();await instruction().fill("Old steering text");await instruction().press("Enter");await expect(instruction()).toHaveValue("");await instruction().fill("New steering draft");await expect(surface()).toContainText("Acceptance unknown");expect(posts()).toHaveLength(1);const first=posts()[0]!;expect(JSON.parse(first.body).text).toBe("Old steering text");
  await surface().getByRole("button",{name:"Retry original command",exact:true}).click();await expect(surface().getByRole("listitem",{name:"Steering receipt"})).toContainText("Accepted by center");expect(posts()).toHaveLength(2);expect(posts()[1]!.key).toBe(first.key);expect(posts()[1]!.body).toBe(first.body);await expect(instruction()).toHaveValue("New steering draft");await expect(composer()).toHaveValue("Normal composer draft");expect(preview.first.requests.filter(r=>r.method==="POST"&&r.path.endsWith("/turns"))).toHaveLength(0);expect(preview.first.requests.some(r=>r.path.endsWith("/cancel"))).toBe(false);
 });
 await check("accepted-unresolved close protection; explicit observation resolves without claiming model compliance",async()=>{
  await hide();await page.locator('[id="tab-conversation:chat-2"]').focus();await page.keyboard.press("Delete");const warning=page.getByRole("dialog",{name:"Leave unconfirmed steering receipts?",exact:true});await expect(warning).toBeVisible();await warning.getByRole("button",{name:"Keep this page",exact:true}).click();await open();await expect(instruction()).toHaveValue("New steering draft");preview.consume("chat-2-task-1");await refresh();await expect(surface().getByRole("listitem",{name:"Steering receipt"})).toContainText("Consumption observed");
 });
 await check("plugin disable/enable retains local draft and never auto-resubmits or reads on restoration",async()=>{
  await hide();await page.getByRole("button",{name:"Extensions and appearance",exact:true}).click();await page.getByRole("button",{name:"Disable flow.conversation-steering",exact:true}).click();await page.keyboard.press("Escape");const before=preview.calls.length;
  await page.getByRole("button",{name:"Extensions and appearance",exact:true}).click();await page.getByRole("button",{name:"Enable flow.conversation-steering",exact:true}).click();await page.keyboard.press("Escape");expect(preview.calls).toHaveLength(before);await open();await expect(instruction()).toHaveValue("New steering draft");expect(posts()).toHaveLength(2);
 });
 await check("offline invalidates in-flight ACK without clearing original receipt or new draft",async()=>{
  preview.holdNext();await instruction().fill("Held steering");await instruction().press("Enter");await expect(instruction()).toHaveValue("");await instruction().fill("Draft after held write");await expect.poll(()=>posts().length).toBe(3);await context.setOffline(true);await expect(surface()).toContainText("Steering access is unavailable");preview.release();await context.setOffline(false);await expect(instruction()).toBeVisible();await expect(instruction()).toHaveValue("Draft after held write");await expect(surface()).toContainText("Acceptance unknown");const before=posts().length;await refresh();expect(posts()).toHaveLength(before);await surface().getByRole("button",{name:"Retry original command",exact:true}).click();await expect(surface().getByRole("listitem",{name:"Steering receipt"}).last()).toContainText("Accepted by center");expect(posts().at(-1)!.key).toBe(posts()[2]!.key);
 });
 await check("390 light/dark reduced-motion keyboard control remains usable and original composer remains separate",async()=>{
  await page.setViewportSize({width:390,height:844});if(await page.getByRole("button",{name:"Hide chat list",exact:true}).isVisible())await page.getByRole("button",{name:"Hide chat list",exact:true}).click();await instruction().focus();await instruction().press("ControlOrMeta+a");await instruction().press("ArrowRight");await instruction().press("Shift+Enter");await expect(instruction()).toHaveValue("Draft after held write\n");expect(await surface().evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);await page.screenshot({path:out+label+"-light-390.png"});await hide();await page.getByRole("button",{name:"Use dark theme",exact:true}).click();await open();await page.screenshot({path:out+label+"-dark-390.png"});await instruction().focus();await page.keyboard.press("Tab");expect(await surface().evaluate(el=>el.contains(document.activeElement))).toBe(true);await expect(composer()).toHaveValue("Normal composer draft");
 });
 await check("explicit chat close discards only its warned unknown recovery; another pane keeps its own draft",async()=>{
  await hide();await select(3);await open("chat-3");preview.loseNext();await instruction().fill("B uncertain command");await instruction().press("Enter");await expect(surface()).toContainText("Acceptance unknown");await hide();await page.locator('[id="tab-conversation:chat-3"]').focus();await page.keyboard.press("Delete");const warning=page.getByRole("dialog",{name:"Leave unconfirmed steering receipts?",exact:true});await expect(warning).toBeVisible();await warning.getByRole("button",{name:"Leave and discard local recovery",exact:true}).click();await expect(pane("chat-3")).toHaveCount(0);
  await select(3);await open("chat-3");await expect(instruction()).toHaveValue("");await expect(surface().getByRole("listitem",{name:"Steering receipt"})).toHaveCount(0);await hide();await select(2);await open();await expect(instruction()).toHaveValue("Draft after held write\n");
 });
 await check("change-connection warns before losing page-local recovery and same IDs start empty",async()=>{
  await hide();await page.getByRole("button",{name:"Change connection",exact:true}).click();const warning=page.getByRole("dialog",{name:"Leave unconfirmed steering receipts?",exact:true});await expect(warning).toBeVisible();await warning.getByRole("button",{name:"Keep this page",exact:true}).click();await open();await expect(instruction()).toHaveValue("Draft after held write\n");await hide();await page.getByRole("button",{name:"Change connection",exact:true}).click();await warning.getByRole("button",{name:"Leave and discard local recovery",exact:true}).click();await page.getByLabel("Center URL",{exact:true}).fill(preview.centers[1]!);await page.getByLabel("Owner token",{exact:true}).fill("flow-fixture-only");await page.getByRole("button",{name:"Connect workspace",exact:true}).click();await select(2);await open();await expect(instruction()).toHaveValue("");await expect(surface().getByRole("listitem",{name:"Steering receipt"})).toHaveCount(0);expect(preview.calls.filter(c=>c.center===1&&c.method==="POST")).toHaveLength(0);
 });
 await check("server unavailable remains unavailable despite plugin activation; normal Queue and Send are unchanged",async()=>{
  preview.disable(true);await refresh();await instruction().fill("Cannot send to unavailable server");await expect(surface().getByRole("button",{name:"Send steering",exact:true})).toBeDisabled();await instruction().press("Enter");expect(preview.calls.filter(c=>c.center===1&&c.method==="POST")).toHaveLength(0);await hide();await pane().getByRole("radio",{name:"Queue next",exact:true}).check();await composer().fill("Ordinary queued text");await composer().press("Enter");await expect(composer()).toHaveValue("");await expect.poll(()=>preview.second.requests.filter(r=>r.method==="POST"&&r.path.endsWith("/queue")).length).toBe(1);expect(preview.second.requests.some(r=>r.path.endsWith("/cancel"))).toBe(false);
  await select(8);await composer("chat-8").fill("Ordinary follow-up");await composer("chat-8").press("Enter");await expect(composer("chat-8")).toHaveValue("");await expect.poll(()=>preview.second.requests.filter(r=>r.method==="POST"&&r.path.endsWith("chat-8/turns")).length).toBe(1);
 });
 expect(errors).toEqual([]);
}catch(error){failure=error instanceof Error?error.stack??error.message:String(error);console.error(failure);await page.screenshot({path:out+label+"-failure.png"});}
finally{
 const paths:string[]=JSON.parse(await readFile(out+"take-receipt.json","utf8")).claim.scope.filter((p:string)=>p.startsWith("apps/"));const hashes=Object.fromEntries(await Promise.all(paths.map(async p=>[p,createHash("sha256").update(await readFile(root+p)).digest("hex")])));
 await writeFile(out+label+"-browser.json",JSON.stringify({at:new Date().toISOString(),sourceCommit:execFileSync("git",["rev-parse","HEAD"],{cwd:root,encoding:"utf8"}).trim(),hashes,production,checks,errors,failure,calls:preview.calls},null,2));await browser.close();await preview.close();
}
if(failure)process.exitCode=1;
