from pathlib import Path
import json,subprocess,hashlib,shutil,datetime,sys
root=Path('/Users/citrine/Projects/AgentHarness/Flow-worktrees/web-context-history');home=Path('/private/tmp/context-history-wiring-20261007');name=sys.argv[1];base=home/name;base.mkdir();previous=home/'types-1';old=Path('/private/tmp/context-history-20261007/types-1')
(base/'run.py').write_bytes((previous/'run.py').read_bytes());(base/'sandbox.sb').write_text((previous/'sandbox.sb').read_text().replace(str(previous),str(base)))
b=json.loads((previous/'binding.json').read_text());extra=[]
if name.startswith('types'):
 cfg=json.loads((previous/'types.json').read_text());cfg['compilerOptions']['types']=['node'];supplement=json.loads((home/'alias-supplement.json').read_text());cfg['compilerOptions']['paths'].update(supplement['paths']);vite=Path(cfg['compilerOptions']['paths']['vite'][0])/'client.d.ts';cfg['files'].extend([str(vite),str(root/'apps/web/src/env.d.ts')]);(base/'types.json').write_text(json.dumps(cfg,indent=2)+'\n');b['command'][-1]=str(base/'types.json');extra=[vite,base/'types.json']+[Path(p['path']) for p in supplement['pins']]
else:b['command']=['/opt/homebrew/opt/node@24/bin/node','--test','--test-isolation=none','--test-concurrency=1',str(root/'apps/web/src/conversation-context-history/binding.test.ts')]
cmd=['/opt/homebrew/opt/node@24/bin/node','--env-file=/tmp/flow-coordination.env','/Users/citrine/Projects/AgentHarness/Flow/apps/execution-dashboard/src/coordination/cli.mjs','list'];live=json.loads(subprocess.check_output(cmd,text=True));own=next(c for c in live['claims'] if c['claimId']==b['claim']);assert own['version']==2 and own['state']=='active'
assert not [c for c in live['claims'] if c['claimId']!=own['claimId'] and c['state']!='released' and any(a==z or a.startswith(z+'/') or z.startswith(a+'/') for a in own['scope'] for z in c['scope'])]
(base/'live.json').write_text(json.dumps({'state':'available','observedAt':live['observedAt'],'claims':[own],'allLedgerScopesChecked':True,'conflicts':[]},indent=2)+'\n')
canonical=Path('/Users/citrine/Projects/AgentHarness/Flow-worktrees/web-platform-management/docs/evidence/web-platform/host-i01-newpair-queue-20261007/current.json');raw=canonical.read_bytes();c=json.loads(raw);f=c['forwardAdmission'];total=sum(f['termsBytes'].values());assert total==f['minimumFreshFreeBytes']==c['floor'];free=shutil.disk_usage(base).free;assert free>=total
(base/'resource.json').write_text(json.dumps({'observedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'canonicalAt':f['at'],'canonicalSha256':hashlib.sha256(raw).hexdigest(),'termsBytes':{k:v for k,v in f['termsBytes'].items() if v},'sum':total,'minimumFreshFreeBytes':f['minimumFreshFreeBytes'],'topLevelFloor':c['floor'],'free':free},indent=2)+'\n')
b.update(head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=root,text=True).strip(),declaredDirty=subprocess.check_output(['git','status','--porcelain'],cwd=root,text=True).strip(),live=str(base/'live.json'),startFreeBytes=total,stopFreeBytes=total-8388608)
paths=[Path(p['path']) for p in b['pins'] if not p['path'].startswith(str(home))];paths+=list((root/'packages/interaction/src').rglob('*.ts'))+extra+[base/'run.py',base/'sandbox.sb'];b['pins']=[{'path':str(p),'realpath':str(p.resolve(strict=True)),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in dict.fromkeys(paths)];(base/'binding.json').write_text(json.dumps(b,indent=2)+'\n');print(json.dumps({'base':str(base),'pins':len(b['pins']),'floor':total,'free':free,'canonicalAt':f['at']}))
